### PR TITLE
Work-around for "outer border - second hand line in IE" issue

### PR DESCRIPTION
**Pull request by RavanH**
Hi,

coolclock-issue-with-seconds-hand

The issue causing a line or shadow originiating from the 3 o'clock point following the second hand (or minute hand if lacking a second hand) as described on  https://github.com/simonbaird/CoolClock/issues/11 can be fixed (or rather worked around) by removing the outer border completely in IE. Just like the decorations...

Not a real fix but still rather effective :) as tested live in the CoolClock WordPress plugin http://wordpress.org/extend/plugins/coolclock/

Please include for 3+

Thanks!

### CODE REVIEW

**Comment by RavanH** [comment]
Oh, plus some changes to the demos to make IE access excanvas.js on the randomibis demo site.

**Comment by henrahmagix** [comment]
@RavanH I'm currently doing some IE testing and came across a _potential (I'm pretty certain!)_ fix! The `fullCircleAt()` method was only calling `canvasContext.beginPath()` if the browser _wasn't_ IE. Removing that conditional stopped the lines that I was seing being drawn, lines that were similar to the ones you noted.

I will add this to my fork and get a pull-request soon. Sorry for being so lack luster!

**Comment by RavanH** [comment]
@henrahmagix Fantastic! Much better than my quick workaround :)

**Comment by henrahmagix** [comment]
Thanks @RavanH! I will reopen this until the fix gets merged in so others can see.

EDIT: woops, should have noticed it was a pull-request. I'll copy your description into a new issue.

**Pull request closed without merging**
