### PR TITLE
Call init() correctly when calling window.CoolClock()

### PR DESCRIPTION
**Pull request by henrahmagix**
`Uncaught TypeError: Object [object Window] has no method 'init'`

'this' is the window object, not the CoolClock object.

### CODE REVIEW

**Comment by henrahmagix** [comment]
My bad - should have realised it was a constructor to be used like `new CoolClock()`.

**Comment by simonbaird** [comment]
ok :)

**Comment by simonbaird** [comment]
Ps, if you feel like doing some hacking, I think using data-\* attributes would be much nicer than packing the ':' delimited fields into the class.

Eg, instead of this mess: &lt;canvas id="clockid" class="CoolClock:Skin:Radius:noSeconds:GMTOffset"&gt;

Something more like this:
&lt;canvas id="clockid" class="CoolClock" data-coolclock-skin="myskin" data-coolclock-radius="50" data-coolclock-no-seconds="true" ... /&gt;

**Comment by henrahmagix** [comment]
:+1: 

I'm currently using this for a project at work and have many changes that I'd like to implement. I'll make that one of them =)

**Comment by henrahmagix** [comment]
I have just been given permission to work on this in my work time! Woohoo!

I have lots of things I'd like to implement, mainly:
- Allow 1-12 on the clock face,
- Allow clock hands to be quadrilaterals (so they can be drawn as pointers),
- Allow stroke and fill on clock hands and all decorations,
- Refactor `class="CoolClock:Skin:Radius:etc"` into `data-*` attributes like you mentioned above.

In light of that, may I become a collaborator on this project please? =)

**Pull request closed without merging**
